export const defaultPlanId = "free"

export const pricingPlans = [
  {
    id: "free",
    name: "Free",
    description: "Perfect for getting started with your developer portfolio",
    price: "$0",
    priceIntervalName: "forever",
    stripe_price_id: null,
    features: [
      "Up to 3 projects",
      "Automated screenshots",
      "Tech stack tagging",
      "Public portfolio page",
      "Contact form",
      "Up to 5 testimonials",
      "Social media links",
    ],
  },
  {
    id: "starter_ltd",
    name: "Starter LTD",
    description: "One-time payment for expanded portfolio features",
    price: "$15",
    priceIntervalName: "lifetime",
    stripe_price_id: "price_1Rsq6aCl8zxGQFLZR8a54voV",
    stripe_product_id: "prod_starter_ltd",
    features: [
      "Everything in Free",
      "Up to 10 projects",
      "Unlimited testimonials",
      "Hackathon certificates",
      "Advanced analytics",
      "Priority support",
    ],
  },
  {
    id: "unlimited_ltd",
    name: "Unlimited LTD",
    description: "One-time payment for unlimited portfolio power",
    price: "$55",
    priceIntervalName: "lifetime",
    stripe_price_id: "price_1RsqwPCl8zxGQFLZ1sAg7nT6",
    stripe_product_id: "prod_unlimited_ltd",
    features: [
      "Everything in Starter LTD",
      "Unlimited projects",
      "Custom domain support",
      "Client portals",
      "White-label options",
      "SEO optimization",
      "Premium support",
    ],
  },
]
